

```{r,fig.height=3,fig.width=4}
data.frame(x=c(1:10,1:10),y=c(1:10,seq(1,5.5,by=0.5)),grp=factor(rep(c("A","B"),each=10))) %>%
  ggplot(aes(y=y,x=x,col=grp))+
    geom_line(show.legend=FALSE,size=1)+
      theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())
```

```{r,fig.height=3,fig.width=4}
data.frame(x=c(1:10,1:10),y=c(1:10,3:12),grp=factor(rep(c("A","B"),each=10))) %>%
  ggplot(aes(y=y,x=x,col=grp))+
    geom_line(show.legend=FALSE,size=1)+    
  theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())
```



```{r,fig.height=3,fig.width=4}
data.frame(x=c(1:10),y=c(1:10)) %>%
  ggplot(aes(y=y,x=x))+
    geom_line(show.legend=FALSE,size=1)+    
  theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())
```



```{r,fig.height=3,fig.width=4}
data.frame(x=c(1:10),y=log(c(1:10))) %>%
  ggplot(aes(y=y,x=x))+
    geom_line(show.legend=FALSE,size=1)+    
  theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())
```


```{r,fig.height=3,fig.width=4}
data.frame(x=1:10,y=(-5+c(1:10))**2) %>%
  ggplot(aes(y=y,x=x))+
    geom_line(show.legend=FALSE,size=1)+    
  theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())
```


```{r,fig.height=3,fig.width=4}
data.frame(x=1:3,y=c(5,2,4)) %>%
  ggplot(aes(y=y,x=x,col=factor(x)))+
    geom_point(show.legend=FALSE,size=10,pch=17)+    
  theme_light()+
        labs(x="",y="")+
          theme(axis.text = element_blank())+
            scale_color_brewer(palette="Dark2")+
  ylim(1,6)+
    xlim(0.5,3.5)
```
